---
title: Getting started with Git
hero_image: images/banner.png
description: Learn how to use Git and GitHub from the command line on Linux, Mac OS
  and Windows
original_url: https://raspberrypi.org/learning/getting-started-with-git
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-0, phys-comp-0, manufacture-0, community-2
interests: ''
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: What is Git?
- title: Getting Git
  completion:
  - engaged
- title: Setting up Git
- title: Creating your first magic school bag
- title: Adding your books
- title: Adding more books and travelling in time
- title: Making major changes
- title: Working with a sky-bag
- title: Collaborative working
- title: GitHub issues
- title: Pull requests
  completion:
  - internal
- title: What next?
